"""metadata

Revision ID: 076ec288e768
Revises: f96cb3b2c523
Create Date: 2022-04-01 13:09:19.609128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "076ec288e768"
down_revision = "f96cb3b2c523"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metadata", sa.Column("id", sa.Integer(), autoincrement=True, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metadata", "id")
    # ### end Alembic commands ###
