"""metadata

Revision ID: c6bc36f6a795
Revises: f96cb3b2c523
Create Date: 2022-04-15 15:33:41.515679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = "c6bc36f6a795"
down_revision = "f96cb3b2c523"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence("metadata_id_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metadata",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('metadata_id_seq')"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metadata", "id")
    # ### end Alembic commands ###
